services:
  servidorweb:
    image: httpd:2.4
    ports:
      - "80:80"
    volumes:
      - ./projecteVideojocs_front:/usr/local/apache2/htdocs

  node:
    image: node:16
    ports:
      - "3000:3000"
    volumes:
      - ./projecteVideojocs_server:/app
    working_dir: /app
    command: npm start
    depends_on:
      - db

  db:
    image: mariadb:10.7
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=iesmanacorroot
      - MYSQL_USER=daw
      - MYSQL_PASSWORD=iesmanacor
      - MYSQL_DATABASE=practicavideojocs
    volumes:
      - ./volums/mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8083:80"
    environment:
      - PMA_HOST=db