INSERT INTO creator (`name`, last_name, birth_date, country, image_url)
VALUES ('Robert', 'Topala', '1987-02-23', 'Sweden', '/creators/robtop.jpg');
INSERT INTO creator (`name`, last_name, birth_date, country, image_url) VALUES ('Shigeru', 'Miyamoto', '1952-11-16', 'Japan', '/creators/miyamoto.jpg');
INSERT INTO creator (`name`, last_name, birth_date, country, image_url) VALUES ('Hideo', 'Kojima', '1963-08-24', 'Japan', '/creators/kojima.jpg');
INSERT INTO creator (`name`, last_name, birth_date, country, image_url) VALUES ('Yoko', 'Taro', '1970-01-06', 'Japan', '/creators/yokotaro.jpg');
INSERT INTO creator (`name`, last_name, birth_date, country, image_url) VALUES ('Hidetaka', 'Miyazaki', '1974-01-01', 'Japan', '/creators/miyazaki.jpg');
INSERT INTO creator (`name`, last_name, birth_date, country, image_url) VALUES ('Gabe', 'Newell', '1962-11-03', 'United States', '/creators/gabe.jpg');
INSERT INTO creator (`name`, last_name, birth_date, country, image_url) VALUES ('Todd', 'Howard', '1971-04-25', 'United States', '/creators/todd.jpg');
INSERT INTO creator (`name`, last_name, birth_date, country, image_url) VALUES ('Sid', 'Meier', '1954-02-24', 'Canada', '/creators/sid.jpg');
INSERT INTO creator (`name`, last_name, birth_date, country, image_url) VALUES ('Will', 'Wright', '1960-01-20', 'United States', '/creators/willwright.jpg');
INSERT INTO creator (`name`, last_name, birth_date, country, image_url) VALUES ('Peter', 'Molyneux', '1959-05-05', 'United Kingdom', '/creators/molyneux.jpg');
INSERT INTO creator (`name`, last_name, birth_date, country, image_url) VALUES ('Tim', 'Schafer', '1967-07-26', 'United States', '/creators/schafer.jpg');
INSERT INTO creator (`name`, last_name, birth_date, country, image_url) VALUES ('Jenova', 'Chen', '1981-01-01', 'China', '/creators/jenova.jpg');
INSERT INTO creator (`name`, last_name, birth_date, country, image_url) VALUES ('Fumito', 'Ueda', '1970-01-01', 'Japan', '/creators/ueda.jpg');
INSERT INTO creator (`name`, last_name, birth_date, country, image_url) VALUES ('Ken', 'Levine', '1966-01-01', 'United States', '/creators/levine.jpg');
INSERT INTO creator (`name`, last_name, birth_date, country, image_url) VALUES ('Warren', 'Spector', '1955-01-01', 'United States', '/creators/spector.jpg');
INSERT INTO creator (`name`, last_name, birth_date, country, image_url) VALUES ('Yu', 'Suzuki', '1958-06-10', 'Japan', '/creators/yusuzuki.jpg');
INSERT INTO creator (`name`, last_name, birth_date, country, image_url) VALUES ('Koji', 'Igarashi', '1969-07-13', 'Japan', '/creators/iga.jpg');
INSERT INTO creator (`name`, last_name, birth_date, country, image_url) VALUES ('Yuji', 'Naka', '1965-09-17', 'Japan', '/creators/yujinka.jpg');
INSERT INTO creator (`name`, last_name, birth_date, country, image_url) VALUES ('Kazutaka', 'Kodaka', '1980-01-01', 'Japan', '/creators/kodaka.jpg');
INSERT INTO creator (`name`, last_name, birth_date, country, image_url) VALUES ('Masahiro', 'Sakurai', '1970-08-03', 'Japan', '/creators/sakurai.jpg');
INSERT INTO creator (`name`, last_name, birth_date, country, image_url) VALUES ('Eiji', 'Aonuma', '1963-01-01', 'Japan', '/creators/aonuma.jpg');
INSERT INTO creator (`name`, last_name, birth_date, country, image_url) VALUES ('Naoki', 'Yoshida', '1973-01-01', 'Japan', '/creators/yoshida.jpg');
INSERT INTO creator (`name`, last_name, birth_date, country, image_url) VALUES ('Tetsuya', 'Nomura', '1970-10-08', 'Japan', '/creators/nomura.jpg');
INSERT INTO creator (`name`, last_name, birth_date, country, image_url) VALUES ('Yasumi', 'Matsuno', '1965-01-01', 'Japan', '/creators/matsuno.jpg');
INSERT INTO creator (`name`, last_name, birth_date, country, image_url) VALUES ('Toby', 'Fox', '1991-10-11', 'United States', '/creators/tobyfox.jpg');
INSERT INTO creator (`name`, last_name, birth_date, country, image_url) VALUES ('Eric', 'Barone', '1987-12-03', 'United States', '/creators/concernedape.jpg');
INSERT INTO creator (`name`, last_name, birth_date, country, image_url) VALUES ('Jonatan', 'Soderstrom', '1985-01-01', 'Sweden', '/creators/cactus.jpg');
INSERT INTO creator (`name`, last_name, birth_date, country, image_url) VALUES ('Edmund', 'McMillen', '1980-03-02', 'United States', '/creators/mcmillen.jpg');
INSERT INTO creator (`name`, last_name, birth_date, country, image_url) VALUES ('Phil', 'Fish', '1984-01-01', 'Canada', '/creators/philfish.jpg');
INSERT INTO creator (`name`, last_name, birth_date, country, image_url) VALUES ('Jonathan', 'Blow', '1971-01-01', 'United States', '/creators/jonblow.jpg');
INSERT INTO creator (`name`, last_name, birth_date, country, image_url) VALUES ('Notch', 'Persson', '1979-06-01', 'Sweden', '/creators/notch.jpg');
INSERT INTO creator (`name`, last_name, birth_date, country, image_url) VALUES ('Rami', 'Ismail', '1988-01-01', 'Netherlands', '/creators/rami.jpg');
INSERT INTO creator (`name`, last_name, birth_date, country, image_url) VALUES ('Cliff', 'Bleszinski', '1975-02-12', 'United States', '/creators/cliffy.jpg');
INSERT INTO creator (`name`, last_name, birth_date, country, image_url) VALUES ('Jordan', 'Mechner', '1964-06-04', 'United States', '/creators/mechner.jpg');
INSERT INTO creator (`name`, last_name, birth_date, country, image_url) VALUES ('Ron', 'Gilbert', '1964-01-01', 'United States', '/creators/rongilbert.jpg');
INSERT INTO creator (`name`, last_name, birth_date, country, image_url) VALUES ('Dave', 'Gilbert', '1978-01-01', 'United States', '/creators/davegilbert.jpg');
INSERT INTO creator (`name`, last_name, birth_date, country, image_url) VALUES ('Amy', 'Hennig', '1964-01-01', 'United States', '/creators/hennig.jpg');
INSERT INTO creator (`name`, last_name, birth_date, country, image_url) VALUES ('Kim', 'Swift', '1983-01-01', 'United States', '/creators/kimswift.jpg');
INSERT INTO creator (`name`, last_name, birth_date, country, image_url) VALUES ('Roberta', 'Williams', '1953-02-16', 'United States', '/creators/roberta.jpg');
INSERT INTO creator (`name`, last_name, birth_date, country, image_url) VALUES ('Jane', 'Jensen', '1963-01-01', 'United States', '/creators/jenjensen.jpg');
INSERT INTO creator (`name`, last_name, birth_date, country, image_url) VALUES ('Brenda', 'Romero', '1966-01-01', 'United States', '/creators/brenda.jpg');
INSERT INTO creator (`name`, last_name, birth_date, country, image_url) VALUES ('Ikumi', 'Nakamura', '1984-01-01', 'Japan', '/creators/ikumi.jpg');
INSERT INTO creator (`name`, last_name, birth_date, country, image_url) VALUES ('Yoko', 'Shimomura', '1967-10-19', 'Japan', '/creators/shimomura.jpg');
INSERT INTO creator (`name`, last_name, birth_date, country, image_url) VALUES ('Nobuo', 'Uematsu', '1959-03-21', 'Japan', '/creators/uematsu.jpg');
INSERT INTO creator (`name`, last_name, birth_date, country, image_url) VALUES ('Koji', 'Kondo', '1961-08-13', 'Japan', '/creators/kondo.jpg');
INSERT INTO creator (`name`, last_name, birth_date, country, image_url) VALUES ('Masashi', 'Hamauzu', '1971-01-01', 'Japan', '/creators/hamauzu.jpg');
INSERT INTO creator (`name`, last_name, birth_date, country, image_url) VALUES ('Yoji', 'Shinkawa', '1971-01-01', 'Japan', '/creators/shinkawa.jpg');
INSERT INTO creator (`name`, last_name, birth_date, country, image_url) VALUES ('Fumihiko', 'Yasuda', '1978-01-01', 'Japan', '/creators/yasuda.jpg');
INSERT INTO creator (`name`, last_name, birth_date, country, image_url) VALUES ('Kazunori', 'Yamauchi', '1964-08-23', 'Japan', '/creators/yamauchi.jpg');
INSERT INTO creator (`name`, last_name, birth_date, country, image_url) VALUES ('Michel', 'Ancel', '1972-01-01', 'France', '/creators/ancel.jpg');